language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - "pip install -r requirements.txt"
  - "pip install coverage"
script: coverage run --source=ftpretty setup.py test
